from typing import Any

from .._evaluable import _Evaluable

class Attribute(_Evaluable):

  def get(self) -> Any: ...
  def set(self, value: Any) -> None: ...
  def slide(self, value: Any, time: int) -> None: ...
  
  @property
  def sliding(self) -> bool: ...
