from typing import List, Optional, Tuple

from ..evaluable import Evaluable
from ..constants import ACTIVE, CHANNEL_TYPE
from .attributes.float_attribute import FloatAttribute
from .plugin import Plugin
from .sample import Sample

class ChannelBase(Evaluable):

  def bytes_to_seconds(self, bytes: int) -> float: ...
  def free(self): ...
  def get_data(self, length: int) -> bytes: ...
  def get_length(self, mode: int = ...) -> int: ...
  def get_levels(self, length: float, flags: int) -> List[float]: ...
  def get_position(self, mode: int = ...) -> int: ...
  def lock(self) -> bool: ...
  def pause(self) -> bool: ...
  def seconds_to_bytes(self, secs: float) -> int: ...
  def stop(self) -> bool: ...
  def unlock(self) -> bool: ...

  @property
  def default_frequency(self) -> int: ...
  
  @property
  def channels(self) -> int: ...
  
  @property
  def type(self) -> CHANNEL_TYPE: ...
  
  @property
  def resolution(self) -> int: ...
  
  @property
  def plugin(self) -> Optional[Plugin]: ...
  
  @property
  def name(self) -> str: ...
  
  @property
  def sample(self) -> Optional[Sample]: ...
  
  @property
  def level(self) -> Tuple[int, int]: ...
  
  @property
  def active(self) -> ACTIVE: ...
  
  @property
  def data_available(self) -> int: ...
  
  @property
  def flags(self) -> int: ...

  @property
  def frequency(self) -> FloatAttribute: ...

  @property
  def granularity(self) -> FloatAttribute: ...

  @property
  def pan(self) -> FloatAttribute: ...

  @property
  def src(self) -> FloatAttribute: ...

  @property
  def volume(self) -> FloatAttribute: ...
