from .input_device import InputDevice

class InputDeviceEnumerator:

  def __getitem__(self, key: int) -> InputDevice: ...
  def __iter__(self) -> "InputDeviceEnumerator": ...
  def __next__(self) -> InputDevice: ...
  
  @property
  def default(self) -> InputDevice: ...
  