from .output_device import OutputDevice

class OutputDeviceEnumerator:

  def __getitem__(self, key: int) -> OutputDevice: ...
  def __iter__(self) -> "OutputDeviceEnumerator": ...
  def __next__(self) -> OutputDevice: ...
  
  @property
  def default(self) -> OutputDevice: ...
  