from .BASS cimport bass

# only forward constants that are required/important at Python level

BASS_OK = bass._BASS_OK
BASS_ERROR_MEM = bass._BASS_ERROR_MEM
BASS_ERROR_FILEOPEN = bass._BASS_ERROR_FILEOPEN
BASS_ERROR_DRIVER = bass._BASS_ERROR_DRIVER
BASS_ERROR_BUFLOST = bass._BASS_ERROR_BUFLOST
BASS_ERROR_HANDLE = bass._BASS_ERROR_HANDLE
BASS_ERROR_FORMAT = bass._BASS_ERROR_FORMAT
BASS_ERROR_POSITION = bass._BASS_ERROR_POSITION
BASS_ERROR_INIT = bass._BASS_ERROR_INIT
BASS_ERROR_START = bass._BASS_ERROR_START
BASS_ERROR_SSL = bass._BASS_ERROR_SSL
BASS_ERROR_ALREADY = bass._BASS_ERROR_ALREADY
BASS_ERROR_NOCHAN = bass._BASS_ERROR_NOCHAN
BASS_ERROR_ILLTYPE = bass._BASS_ERROR_ILLTYPE
BASS_ERROR_ILLPARAM = bass._BASS_ERROR_ILLPARAM
BASS_ERROR_NO3D = bass._BASS_ERROR_NO3D
BASS_ERROR_NOEAX = bass._BASS_ERROR_NOEAX
BASS_ERROR_DEVICE = bass._BASS_ERROR_DEVICE
BASS_ERROR_NOPLAY = bass._BASS_ERROR_NOPLAY
BASS_ERROR_FREQ = bass._BASS_ERROR_FREQ
BASS_ERROR_NOTFILE = bass._BASS_ERROR_NOTFILE
BASS_ERROR_NOHW = bass._BASS_ERROR_NOHW
BASS_ERROR_EMPTY = bass._BASS_ERROR_EMPTY
BASS_ERROR_NONET = bass._BASS_ERROR_NONET
BASS_ERROR_CREATE = bass._BASS_ERROR_CREATE
BASS_ERROR_NOFX = bass._BASS_ERROR_NOFX
BASS_ERROR_NOTAVAIL = bass._BASS_ERROR_NOTAVAIL
BASS_ERROR_DECODE = bass._BASS_ERROR_DECODE
BASS_ERROR_DX = bass._BASS_ERROR_DX
BASS_ERROR_TIMEOUT = bass._BASS_ERROR_TIMEOUT
BASS_ERROR_FILEFORM = bass._BASS_ERROR_FILEFORM
BASS_ERROR_SPEAKER = bass._BASS_ERROR_SPEAKER
BASS_ERROR_VERSION = bass._BASS_ERROR_VERSION
BASS_ERROR_CODEC = bass._BASS_ERROR_CODEC
BASS_ERROR_ENDED = bass._BASS_ERROR_ENDED
BASS_ERROR_BUSY = bass._BASS_ERROR_BUSY
BASS_ERROR_UNKNOWN = bass._BASS_ERROR_UNKNOWN

BASS_DEVICE_8BITS = bass._BASS_DEVICE_8BITS
BASS_DEVICE_MONO = bass._BASS_DEVICE_MONO
BASS_DEVICE_3D = bass._BASS_DEVICE_3D
BASS_DEVICE_LATENCY = bass._BASS_DEVICE_LATENCY
BASS_DEVICE_CPSPEAKERS = bass._BASS_DEVICE_CPSPEAKERS
BASS_DEVICE_SPEAKERS = bass._BASS_DEVICE_SPEAKERS
BASS_DEVICE_NOSPEAKER = bass._BASS_DEVICE_NOSPEAKER
BASS_DEVICE_DMIX = bass._BASS_DEVICE_DMIX
BASS_DEVICE_FREQ = bass._BASS_DEVICE_FREQ

BASS_DEVICE_ENABLED = bass._BASS_DEVICE_ENABLED
BASS_DEVICE_DEFAULT = bass._BASS_DEVICE_DEFAULT
BASS_DEVICE_INIT = bass._BASS_DEVICE_INIT
BASS_DEVICE_LOOPBACK = bass._BASS_DEVICE_LOOPBACK
BASS_DEVICE_TYPE_MASK = bass._BASS_DEVICE_TYPE_MASK
BASS_DEVICE_TYPE_NETWORK = bass._BASS_DEVICE_TYPE_NETWORK
BASS_DEVICE_TYPE_SPEAKERS = bass._BASS_DEVICE_TYPE_SPEAKERS
BASS_DEVICE_TYPE_LINE = bass._BASS_DEVICE_TYPE_LINE
BASS_DEVICE_TYPE_HEADPHONES = bass._BASS_DEVICE_TYPE_HEADPHONES
BASS_DEVICE_TYPE_MICROPHONE = bass._BASS_DEVICE_TYPE_MICROPHONE
BASS_DEVICE_TYPE_HEADSET = bass._BASS_DEVICE_TYPE_HEADSET
BASS_DEVICE_TYPE_HANDSET = bass._BASS_DEVICE_TYPE_HANDSET
BASS_DEVICE_TYPE_DIGITAL = bass._BASS_DEVICE_TYPE_DIGITAL
BASS_DEVICE_TYPE_SPDIF = bass._BASS_DEVICE_TYPE_SPDIF
BASS_DEVICE_TYPE_HDMI = bass._BASS_DEVICE_TYPE_HDMI
BASS_DEVICE_TYPE_DISPLAYPORT = bass._BASS_DEVICE_TYPE_DISPLAYPORT
BASS_DEVICES_AIRPLAY = bass._BASS_DEVICES_AIRPLAY

BASS_OBJECT_DS = bass._BASS_OBJECT_DS
BASS_OBJECT_DS3DL = bass._BASS_OBJECT_DS3DL

DSCAPS_CONTINUOUSRATE = bass._DSCAPS_CONTINUOUSRATE
DSCAPS_EMULDRIVER = bass._DSCAPS_EMULDRIVER
DSCAPS_CERTIFIED = bass._DSCAPS_CERTIFIED
DSCAPS_SECONDARYMONO = bass._DSCAPS_SECONDARYMONO
DSCAPS_SECONDARYSTEREO = bass._DSCAPS_SECONDARYSTEREO
DSCAPS_SECONDARY8BIT = bass._DSCAPS_SECONDARY8BIT
DSCAPS_SECONDARY16BIT = bass._DSCAPS_SECONDARY16BIT

DSCCAPS_EMULDRIVER = bass._DSCCAPS_EMULDRIVER
DSCCAPS_CERTIFIED = bass._DSCCAPS_CERTIFIED

WAVE_FORMAT_1M08 = bass._WAVE_FORMAT_1M08
WAVE_FORMAT_1S08 = bass._WAVE_FORMAT_1S08
WAVE_FORMAT_1M16 = bass._WAVE_FORMAT_1M16
WAVE_FORMAT_1S16 = bass._WAVE_FORMAT_1S16
WAVE_FORMAT_2M08 = bass._WAVE_FORMAT_2M08
WAVE_FORMAT_2S08 = bass._WAVE_FORMAT_2S08
WAVE_FORMAT_2M16 = bass._WAVE_FORMAT_2M16
WAVE_FORMAT_2S16 = bass._WAVE_FORMAT_2S16
WAVE_FORMAT_4M08 = bass._WAVE_FORMAT_4M08
WAVE_FORMAT_4S08 = bass._WAVE_FORMAT_4S08
WAVE_FORMAT_4M16 = bass._WAVE_FORMAT_4M16
WAVE_FORMAT_4S16 = bass._WAVE_FORMAT_4S16

BASS_SAMPLE_8BITS = bass._BASS_SAMPLE_8BITS
BASS_SAMPLE_FLOAT = bass._BASS_SAMPLE_FLOAT
BASS_SAMPLE_MONO = bass._BASS_SAMPLE_MONO
BASS_SAMPLE_LOOP = bass._BASS_SAMPLE_LOOP
BASS_SAMPLE_3D = bass._BASS_SAMPLE_3D
BASS_SAMPLE_SOFTWARE = bass._BASS_SAMPLE_SOFTWARE
BASS_SAMPLE_MUTEMAX = bass._BASS_SAMPLE_MUTEMAX
BASS_SAMPLE_VAM = bass._BASS_SAMPLE_VAM
BASS_SAMPLE_FX = bass._BASS_SAMPLE_FX
BASS_SAMPLE_OVER_VOL = bass._BASS_SAMPLE_OVER_VOL
BASS_SAMPLE_OVER_POS = bass._BASS_SAMPLE_OVER_POS
BASS_SAMPLE_OVER_DIST = bass._BASS_SAMPLE_OVER_DIST

BASS_STREAM_PRESCAN = bass._BASS_STREAM_PRESCAN
BASS_MP3_SETPOS = bass._BASS_MP3_SETPOS
BASS_STREAM_AUTOFREE = bass._BASS_STREAM_AUTOFREE
BASS_STREAM_RESTRATE = bass._BASS_STREAM_RESTRATE
BASS_STREAM_BLOCK = bass._BASS_STREAM_BLOCK
BASS_STREAM_DECODE = bass._BASS_STREAM_DECODE
BASS_STREAM_STATUS = bass._BASS_STREAM_STATUS

BASS_MUSIC_FLOAT = bass._BASS_MUSIC_FLOAT
BASS_MUSIC_MONO = bass._BASS_MUSIC_MONO
BASS_MUSIC_LOOP = bass._BASS_MUSIC_LOOP
BASS_MUSIC_3D = bass._BASS_MUSIC_3D
BASS_MUSIC_FX = bass._BASS_MUSIC_FX
BASS_MUSIC_AUTOFREE = bass._BASS_MUSIC_AUTOFREE
BASS_MUSIC_DECODE = bass._BASS_MUSIC_DECODE
BASS_MUSIC_PRESCAN = bass._BASS_MUSIC_PRESCAN
BASS_MUSIC_CALCLEN = bass._BASS_MUSIC_CALCLEN
BASS_MUSIC_RAMP = bass._BASS_MUSIC_RAMP
BASS_MUSIC_RAMPS = bass._BASS_MUSIC_RAMPS
BASS_MUSIC_SURROUND = bass._BASS_MUSIC_SURROUND
BASS_MUSIC_SURROUND2 = bass._BASS_MUSIC_SURROUND2
BASS_MUSIC_FT2MOD = bass._BASS_MUSIC_FT2MOD
BASS_MUSIC_PT1MOD = bass._BASS_MUSIC_PT1MOD
BASS_MUSIC_NONINTER = bass._BASS_MUSIC_NONINTER
BASS_MUSIC_SINCINTER = bass._BASS_MUSIC_SINCINTER
BASS_MUSIC_POSRESET = bass._BASS_MUSIC_POSRESET
BASS_MUSIC_POSRESETEX = bass._BASS_MUSIC_POSRESETEX
BASS_MUSIC_STOPBACK = bass._BASS_MUSIC_STOPBACK
BASS_MUSIC_NOSAMPLE = bass._BASS_MUSIC_NOSAMPLE

BASS_ASYNCFILE = bass._BASS_ASYNCFILE
BASS_UNICODE = bass._BASS_UNICODE

BASS_SPEAKER_FRONT = bass._BASS_SPEAKER_FRONT
BASS_SPEAKER_REAR = bass._BASS_SPEAKER_REAR
BASS_SPEAKER_CENLFE = bass._BASS_SPEAKER_CENLFE
BASS_SPEAKER_REAR2 = bass._BASS_SPEAKER_REAR2
BASS_SPEAKER_LEFT = bass._BASS_SPEAKER_LEFT
BASS_SPEAKER_RIGHT = bass._BASS_SPEAKER_RIGHT
BASS_SPEAKER_FRONTLEFT = bass._BASS_SPEAKER_FRONTLEFT
BASS_SPEAKER_FRONTRIGHT = bass._BASS_SPEAKER_FRONTRIGHT
BASS_SPEAKER_REARLEFT = bass._BASS_SPEAKER_REARLEFT
BASS_SPEAKER_REARRIGHT = bass._BASS_SPEAKER_REARRIGHT
BASS_SPEAKER_CENTER = bass._BASS_SPEAKER_CENTER
BASS_SPEAKER_LFE = bass._BASS_SPEAKER_LFE
BASS_SPEAKER_REAR2LEFT = bass._BASS_SPEAKER_REAR2LEFT
BASS_SPEAKER_REAR2RIGHT = bass._BASS_SPEAKER_REAR2RIGHT

BASS_RECORD_PAUSE = bass._BASS_RECORD_PAUSE
BASS_RECORD_ECHOCANCEL = bass._BASS_RECORD_ECHOCANCEL
BASS_RECORD_AGC = bass._BASS_RECORD_AGC

BASS_VAM_HARDWARE = bass._BASS_VAM_HARDWARE
BASS_VAM_SOFTWARE = bass._BASS_VAM_SOFTWARE
BASS_VAM_TERM_TIME = bass._BASS_VAM_TERM_TIME
BASS_VAM_TERM_DIST = bass._BASS_VAM_TERM_DIST
BASS_VAM_TERM_PRIO = bass._BASS_VAM_TERM_PRIO

BASS_CTYPE_SAMPLE = bass._BASS_CTYPE_SAMPLE
BASS_CTYPE_RECORD = bass._BASS_CTYPE_RECORD
BASS_CTYPE_STREAM = bass._BASS_CTYPE_STREAM
BASS_CTYPE_STREAM_OGG = bass._BASS_CTYPE_STREAM_OGG
BASS_CTYPE_STREAM_MP1 = bass._BASS_CTYPE_STREAM_MP1
BASS_CTYPE_STREAM_MP2 = bass._BASS_CTYPE_STREAM_MP2
BASS_CTYPE_STREAM_MP3 = bass._BASS_CTYPE_STREAM_MP3
BASS_CTYPE_STREAM_AIFF = bass._BASS_CTYPE_STREAM_AIFF
BASS_CTYPE_STREAM_CA = bass._BASS_CTYPE_STREAM_CA
BASS_CTYPE_STREAM_MF = bass._BASS_CTYPE_STREAM_MF
BASS_CTYPE_STREAM_WAV = bass._BASS_CTYPE_STREAM_WAV
BASS_CTYPE_STREAM_WAV_PCM = bass._BASS_CTYPE_STREAM_WAV_PCM
BASS_CTYPE_STREAM_WAV_FLOAT = bass._BASS_CTYPE_STREAM_WAV_FLOAT
BASS_CTYPE_MUSIC_MOD = bass._BASS_CTYPE_MUSIC_MOD
BASS_CTYPE_MUSIC_MTM = bass._BASS_CTYPE_MUSIC_MTM
BASS_CTYPE_MUSIC_S3M = bass._BASS_CTYPE_MUSIC_S3M
BASS_CTYPE_MUSIC_XM = bass._BASS_CTYPE_MUSIC_XM
BASS_CTYPE_MUSIC_IT = bass._BASS_CTYPE_MUSIC_IT
BASS_CTYPE_MUSIC_MO3 = bass._BASS_CTYPE_MUSIC_MO3

BASS_3DMODE_NORMAL = bass._BASS_3DMODE_NORMAL
BASS_3DMODE_RELATIVE = bass._BASS_3DMODE_RELATIVE
BASS_3DMODE_OFF = bass._BASS_3DMODE_OFF

BASS_3DALG_DEFAULT = bass._BASS_3DALG_DEFAULT
BASS_3DALG_OFF = bass._BASS_3DALG_OFF
BASS_3DALG_FULL = bass._BASS_3DALG_FULL
BASS_3DALG_LIGHT = bass._BASS_3DALG_LIGHT

STREAMFILE_NOBUFFER = bass._STREAMFILE_NOBUFFER
STREAMFILE_BUFFER = bass._STREAMFILE_BUFFER
STREAMFILE_BUFFERPUSH = bass._STREAMFILE_BUFFERPUSH

BASS_FILEDATA_END = bass._BASS_FILEDATA_END

BASS_FILEPOS_CURRENT = bass._BASS_FILEPOS_CURRENT
BASS_FILEPOS_DECODE = bass._BASS_FILEPOS_DECODE
BASS_FILEPOS_DOWNLOAD = bass._BASS_FILEPOS_DOWNLOAD
BASS_FILEPOS_END = bass._BASS_FILEPOS_END
BASS_FILEPOS_START = bass._BASS_FILEPOS_START
BASS_FILEPOS_CONNECTED = bass._BASS_FILEPOS_CONNECTED
BASS_FILEPOS_BUFFER = bass._BASS_FILEPOS_BUFFER
BASS_FILEPOS_SOCKET = bass._BASS_FILEPOS_SOCKET
BASS_FILEPOS_ASYNCBUF = bass._BASS_FILEPOS_ASYNCBUF
BASS_FILEPOS_SIZE = bass._BASS_FILEPOS_SIZE

BASS_ACTIVE_STOPPED = bass._BASS_ACTIVE_STOPPED
BASS_ACTIVE_PLAYING = bass._BASS_ACTIVE_PLAYING
BASS_ACTIVE_STALLED = bass._BASS_ACTIVE_STALLED
BASS_ACTIVE_PAUSED = bass._BASS_ACTIVE_PAUSED
BASS_ACTIVE_PAUSED_DEVICE = bass._BASS_ACTIVE_PAUSED_DEVICE

BASS_DATA_AVAILABLE = bass._BASS_DATA_AVAILABLE
BASS_DATA_FIXED = bass._BASS_DATA_FIXED
BASS_DATA_FLOAT = bass._BASS_DATA_FLOAT
BASS_DATA_FFT256 = bass._BASS_DATA_FFT256
BASS_DATA_FFT512 = bass._BASS_DATA_FFT512
BASS_DATA_FFT1024 = bass._BASS_DATA_FFT1024
BASS_DATA_FFT2048 = bass._BASS_DATA_FFT2048
BASS_DATA_FFT4096 = bass._BASS_DATA_FFT4096
BASS_DATA_FFT8192 = bass._BASS_DATA_FFT8192
BASS_DATA_FFT16384 = bass._BASS_DATA_FFT16384
BASS_DATA_FFT_INDIVIDUAL = bass._BASS_DATA_FFT_INDIVIDUAL
BASS_DATA_FFT_NOWINDOW = bass._BASS_DATA_FFT_NOWINDOW
BASS_DATA_FFT_REMOVEDC = bass._BASS_DATA_FFT_REMOVEDC
BASS_DATA_FFT_COMPLEX = bass._BASS_DATA_FFT_COMPLEX
BASS_DATA_FFT_NYQUIST = bass._BASS_DATA_FFT_NYQUIST

BASS_LEVEL_MONO = bass._BASS_LEVEL_MONO
BASS_LEVEL_STEREO = bass._BASS_LEVEL_STEREO
BASS_LEVEL_RMS = bass._BASS_LEVEL_RMS

BASS_TAG_ID3 = bass._BASS_TAG_ID3
BASS_TAG_ID3V2 = bass._BASS_TAG_ID3V2
BASS_TAG_OGG = bass._BASS_TAG_OGG
BASS_TAG_HTTP = bass._BASS_TAG_HTTP
BASS_TAG_ICY = bass._BASS_TAG_ICY
BASS_TAG_META = bass._BASS_TAG_META
BASS_TAG_APE = bass._BASS_TAG_APE
BASS_TAG_MP4 = bass._BASS_TAG_MP4
BASS_TAG_VENDOR = bass._BASS_TAG_VENDOR
BASS_TAG_LYRICS3 = bass._BASS_TAG_LYRICS3
BASS_TAG_CA_CODEC = bass._BASS_TAG_CA_CODEC
BASS_TAG_MF = bass._BASS_TAG_MF
BASS_TAG_WAVEFORMAT = bass._BASS_TAG_WAVEFORMAT
BASS_TAG_RIFF_INFO = bass._BASS_TAG_RIFF_INFO
BASS_TAG_RIFF_BEXT = bass._BASS_TAG_RIFF_BEXT
BASS_TAG_RIFF_CART = bass._BASS_TAG_RIFF_CART
BASS_TAG_RIFF_DISP = bass._BASS_TAG_RIFF_DISP
BASS_TAG_APE_BINARY = bass._BASS_TAG_APE_BINARY
BASS_TAG_MUSIC_NAME = bass._BASS_TAG_MUSIC_NAME
BASS_TAG_MUSIC_MESSAGE = bass._BASS_TAG_MUSIC_MESSAGE
BASS_TAG_MUSIC_ORDERS = bass._BASS_TAG_MUSIC_ORDERS
BASS_TAG_MUSIC_INST = bass._BASS_TAG_MUSIC_INST
BASS_TAG_MUSIC_SAMPLE = bass._BASS_TAG_MUSIC_SAMPLE

BASS_POS_BYTE = bass._BASS_POS_BYTE
BASS_POS_MUSIC_ORDER = bass._BASS_POS_MUSIC_ORDER
BASS_POS_OGG = bass._BASS_POS_OGG
BASS_POS_INEXACT = bass._BASS_POS_INEXACT
BASS_POS_DECODE = bass._BASS_POS_DECODE
BASS_POS_DECODETO = bass._BASS_POS_DECODETO
BASS_POS_SCAN = bass._BASS_POS_SCAN
BASS_POS_RELATIVE = bass._BASS_POS_RELATIVE

BASS_INPUT_OFF = bass._BASS_INPUT_OFF
BASS_INPUT_ON = bass._BASS_INPUT_ON

BASS_INPUT_TYPE_MASK = bass._BASS_INPUT_TYPE_MASK
BASS_INPUT_TYPE_UNDEF = bass._BASS_INPUT_TYPE_UNDEF
BASS_INPUT_TYPE_DIGITAL = bass._BASS_INPUT_TYPE_DIGITAL
BASS_INPUT_TYPE_LINE = bass._BASS_INPUT_TYPE_LINE
BASS_INPUT_TYPE_MIC = bass._BASS_INPUT_TYPE_MIC
BASS_INPUT_TYPE_SYNTH = bass._BASS_INPUT_TYPE_SYNTH
BASS_INPUT_TYPE_CD = bass._BASS_INPUT_TYPE_CD
BASS_INPUT_TYPE_PHONE = bass._BASS_INPUT_TYPE_PHONE
BASS_INPUT_TYPE_SPEAKER = bass._BASS_INPUT_TYPE_SPEAKER
BASS_INPUT_TYPE_WAVE = bass._BASS_INPUT_TYPE_WAVE
BASS_INPUT_TYPE_AUX = bass._BASS_INPUT_TYPE_AUX
BASS_INPUT_TYPE_ANALOG = bass._BASS_INPUT_TYPE_ANALOG

BASS_DX8_PHASE_NEG_180 = bass._BASS_DX8_PHASE_NEG_180
BASS_DX8_PHASE_NEG_90 = bass._BASS_DX8_PHASE_NEG_90
BASS_DX8_PHASE_ZERO = bass._BASS_DX8_PHASE_ZERO
BASS_DX8_PHASE_90 = bass._BASS_DX8_PHASE_90
BASS_DX8_PHASE_180 = bass._BASS_DX8_PHASE_180

BASS_IOSNOTIFY_INTERRUPT = bass._BASS_IOSNOTIFY_INTERRUPT
BASS_IOSNOTIFY_INTERRUPT_END = bass._BASS_IOSNOTIFY_INTERRUPT_END
