from .attribute_base import AttributeBase

class BoolAttribute(AttributeBase):

  def get(self) -> bool: ...
  def set(self, value: bool) -> bool: ...
  def slide(self, value: bool, time: int) -> bool: ...
  