from ._attribute_base import _AttributeBase

class BoolAttribute(_AttributeBase):

  def get(self) -> bool: ...
  def set(self, value: bool) -> bool: ...
  def slide(self, value: bool, time: int) -> bool: ...
  