from .attribute_base import AttributeBase

class FloatAttribute(AttributeBase):

  def get(self) -> float: ...
  def set(self, value: float) -> bool: ...
  def slide(self, value: float, time: int) -> bool: ...
  