from ._attribute_base import _AttributeBase

class FloatAttribute(_AttributeBase):

  def get(self) -> float: ...
  def set(self, value: float) -> bool: ...
  def slide(self, value: float, time: int) -> bool: ...
  