from ...fx import FX

class Chorus(FX):

  @property 
  def wet_dry_mix(self) -> float: ...

  @wet_dry_mix.setter
  def wet_dry_mix(self, value: float) -> None: ...

  @property 
  def depth(self) -> float: ...

  @depth.setter
  def depth(self, value: float) -> None: ...

  @property 
  def feedback(self) -> float: ...

  @feedback.setter
  def feedback(self, value: float) -> None: ...

  @property 
  def frequency(self) -> float: ...

  @frequency.setter
  def frequency(self, value: float) -> None: ...

  @property 
  def waveform(self) -> int: ...

  @waveform.setter
  def waveform(self, value: int) -> None: ...

  @property 
  def delay(self) -> float: ...

  @delay.setter
  def delay(self, value: float) -> None: ...

  @property 
  def phase(self) -> int: ...

  @phase.setter
  def phase(self, value: int) -> None: ...
