from ...fx import FX

class Distortion(FX):

  @property
  def gain(self) -> float: ...

  @gain.setter
  def gain(self, value: float) -> None: ...

  @property
  def edge(self) -> float: ...

  @edge.setter
  def edge(self, value: float) -> None: ...

  @property
  def post_eq_center_frequency(self) -> float: ...

  @post_eq_center_frequency.setter
  def post_eq_center_frequency(self, value: float) -> None: ...

  @property
  def post_eq_bandwidth(self) -> float: ...

  @post_eq_bandwidth.setter
  def post_eq_bandwidth(self, value: float) -> None: ...

  @property
  def pre_lowpass_cutoff(self) -> float: ...

  @pre_lowpass_cutoff.setter
  def pre_lowpass_cutoff(self, value: float) -> None: ...
