on:
  push: {}
  pull_request: {}

jobs:
  ubuntu:
    runs-on: ${{matrix.os}}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - 
        name: "Download BASS"
        run: |
          wget http://www.un4seen.com/files/bass24-linux.zip
          wget http://www.un4seen.com/files/z/3/tags18-linux.zip
          7z x bass24-linux.zip -obass24-linux -r
          7z x tags18-linux.zip -otags18-linux -r
      - 
        name: "Install python dependencies"
        run: python -m pip install -r requirements-dev.txt
      - 
        name: "Build wheel"
        run: |
          python setup.py build_ext --inplace
          python setup.py bdist_wheel
      - 
        name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl
    strategy:
      matrix:
        include:
          - 
            os: ubuntu-20.04
            python-version: "3.6"
          - 
            os: ubuntu-20.04
            python-version: "3.7"
          - 
            os: ubuntu-20.04
            python-version: "3.8"
          - 
            os: ubuntu-20.04
            python-version: "3.9"
          - 
            os: ubuntu-20.04
            python-version: "3.10"
