on:
  push: {}

jobs:
  build-docs:
    runs-on: windows-2022
    env:
      BASSLIB: "bass24/x64"
      TAGSLIB: "tags18"
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - 
        name: "Download BASS"
        shell: powershell
        run: |
          $wc = New-Object System.Net.WebClient
          $wc.DownloadFile("http://www.un4seen.com/files/bass24.zip", (Join-Path ($pwd).path "bass24.zip"))
          $wc.DownloadFile("http://www.un4seen.com/files/z/3/tags18.zip", (Join-Path ($pwd).path "tags18.zip"))
          & 7z --% x bass24.zip -obass24 -r
          & 7z --% x tags18.zip -otags18 -r
      - 
        name: "Install python dependencies"
        run: python -m pip install -r requirements-dev.txt
      - 
        name: "Build extensions"
        run: |
          python setup.py build_ext --inplace
      - 
        name: "Copy dlls"
        run: |
          cp $BASSLIB/bass.dll doc/bass.dll
      - 
        name: "Build docs"
        run: |
          cd doc
          make html
      - 
        name: "Upload docs"
        uses: actions/upload-artifact@v3
        with:
          name: "Docs"
          path: doc/_build/
